### ISSUE TITLE
update lib

### ISSUE THREAD

**Issue by wwwApp** [wwwApp/resonate#29]
make it so that its loads user data to create lib items

**Comment by wwwApp** [comment]
@claytercek are we working on implementing heart state in database?

**Comment by claytercek** [comment]
> @claytercek are we working on implementing heart state in database?

Yeah, I just finished developing the heart endpoint, it should be live later tonight

**Comment by claytercek** [comment]
@wwwApp Just updated it. Endpoint info can be found [here](https://github.com/claytercek/resonate-server/blob/18cb4c78b7e30f279c5c22bf467a72b8290fd07f/routes/playlist.routes.js#L30). It just toggles whether the given user hearts the given playlist.

I can add a redux action for this tomorrow.
